import { useMemo } from 'react';

// Map of language codes to display names
const LANGUAGE_MAP: Record<string, string> = {
  'en': 'English',
  'es': 'Spanish',
  'fr': 'French',
  'de': 'German',
  'it': 'Italian',
  'pt': 'Portuguese',
  'ru': 'Russian',
  'ja': 'Japanese',
  'ko': 'Korean',
  'zh': 'Chinese',
  'ar': 'Arabic',
  'hi': 'Hindi',
  'nl': 'Dutch',
  'sv': 'Swedish',
  'no': 'Norwegian',
  'da': 'Danish',
  'fi': 'Finnish',
  'pl': 'Polish',
  'tr': 'Turkish',
  'he': 'Hebrew',
  'th': 'Thai',
  'vi': 'Vietnamese',
  'id': 'Indonesian',
  'ms': 'Malay',
  'fa': 'Persian',
  'ur': 'Urdu',
  'bn': 'Bengali',
  'ta': 'Tamil',
  'te': 'Telugu',
  'gu': 'Gujarati',
  'kn': 'Kannada',
  'ml': 'Malayalam',
  'pa': 'Punjabi',
  'si': 'Sinhala',
  'my': 'Burmese',
  'km': 'Khmer',
  'lo': 'Lao',
  'mn': 'Mongolian',
  'ka': 'Georgian',
  'am': 'Amharic',
  'sw': 'Swahili',
  'zu': 'Zulu',
  'af': 'Afrikaans',
  'is': 'Icelandic',
  'ga': 'Irish',
  'cy': 'Welsh',
  'mt': 'Maltese',
  'sq': 'Albanian',
  'mk': 'Macedonian',
  'sr': 'Serbian',
  'hr': 'Croatian',
  'sl': 'Slovenian',
  'sk': 'Slovak',
  'cs': 'Czech',
  'hu': 'Hungarian',
  'ro': 'Romanian',
  'bg': 'Bulgarian',
  'uk': 'Ukrainian',
  'be': 'Belarusian',
  'et': 'Estonian',
  'lv': 'Latvian',
  'lt': 'Lithuanian',
  'el': 'Greek',
  'hy': 'Armenian',
  'az': 'Azerbaijani',
  'kk': 'Kazakh',
  'ky': 'Kyrgyz',
  'uz': 'Uzbek',
  'tg': 'Tajik',
  'tk': 'Turkmen',
  'ps': 'Pashto',
  'ku': 'Kurdish',
  'yi': 'Yiddish',
  'lb': 'Luxembourgish',
  'fo': 'Faroese',
  'sm': 'Samoan',
  'to': 'Tongan',
  'fj': 'Fijian',
  'mi': 'Maori',
  'haw': 'Hawaiian',
  'qu': 'Quechua',
  'ay': 'Aymara',
  'gn': 'Guarani',
  'ht': 'Haitian Creole',
  'jv': 'Javanese',
  'su': 'Sundanese',
  'ceb': 'Cebuano',
  'tl': 'Tagalog',
  'mg': 'Malagasy',
  'ny': 'Chichewa',
  'sn': 'Shona',
  'st': 'Sesotho',
  'tn': 'Tswana',
  'xh': 'Xhosa',
  'yo': 'Yoruba',
  'ig': 'Igbo',
  'ha': 'Hausa',
  'so': 'Somali',
  'om': 'Oromo',
  'ti': 'Tigrinya',
  'aa': 'Afar',
  'ss': 'Swati',
  've': 'Venda',
  'ts': 'Tsonga',
  'dz': 'Dzongkha',
  'bo': 'Tibetan',
  'ne': 'Nepali',
  'as': 'Assamese',
  'or': 'Odia',
  'mr': 'Marathi',
  'sa': 'Sanskrit',
  'sd': 'Sindhi',
  'ks': 'Kashmiri',
  'dv': 'Dhivehi',
  'ug': 'Uyghur',
  'ii': 'Sichuan Yi',
  'za': 'Zhuang',
  'nan': 'Min Nan Chinese',
  'yue': 'Cantonese',
  'hak': 'Hakka Chinese',
  'wuu': 'Wu Chinese',
  'gan': 'Gan Chinese',
  'hsn': 'Xiang Chinese',
  'cjy': 'Jin Chinese',
  'cmn': 'Mandarin Chinese',
  'lzh': 'Literary Chinese',
  'och': 'Old Chinese',
  'ltc': 'Late Middle Chinese',
  'odt': 'Old Dutch',
  'goh': 'Old High German',
  'osx': 'Old Saxon',
  'ang': 'Old English',
  'fro': 'Old French',
  'pro': 'Old Provençal',
  'osp': 'Old Spanish',
  'sga': 'Old Irish',
  'owl': 'Old Welsh',
  'obt': 'Old Breton',
  'xbm': 'Middle Breton',
  'xcl': 'Classical Armenian',
  'xcr': 'Carian',
  'xdc': 'Dacian',
  'xdm': 'Edomite',
  'xeb': 'Eblan',
  'xel': 'Elamite',
  'xet': 'Etruscan',
  'xfa': 'Faliscan',
  'xga': 'Galatian',
  'xgl': 'Galindan',
  'xgr': 'Garza',
  'xha': 'Harami',
  'xhd': 'Hadrami',
  'xhe': 'Hebrew (Ancient)',
  'xhr': 'Hernican',
  'xht': 'Hattic',
  'xhu': 'Hurrian',
  'xib': 'Iberian',
  'xil': 'Illyrian',
  'xlc': 'Lycian',
  'xld': 'Lydian',
  'xle': 'Lepontic',
  'xlg': 'Ligurian',
  'xli': 'Liburnian',
  'xln': 'Alanic',
  'xlo': 'Loup A',
  'xlu': 'Cuneiform Luwian',
  'xly': 'Elymian',
  'xme': 'Median',
  'xmf': 'Mingrelian',
  'xmk': 'Ancient Macedonian',
  'xmr': 'Meroitic',
  'xna': 'Ancient North Arabian',
  'xng': 'Middle Mongolian',
  'xno': 'Anglo-Norman',
  'xoc': 'O\'chi',
  'xod': 'Kokoda',
  'xog': 'Soga',
  'xoi': 'Kominimung',
  'xok': 'Xokleng',
  'xom': 'Komo',
  'xon': 'Konkomba',
  'xoo': 'Xukurú',
  'xop': 'Kopar',
  'xor': 'Korubo',
  'xow': 'Kowaki',
  'xpa': 'Pirriya',
  'xpc': 'Pecheneg',
  'xpe': 'Liberia Kpelle',
  'xpg': 'Phrygian',
  'xpi': 'Pictish',
  'xpj': 'Mpalitjanh',
  'xpk': 'Kulina Pano',
  'xpm': 'Pumpokol',
  'xpn': 'Kapinawá',
  'xpo': 'Pochutec',
  'xpp': 'Puyo-Paekche',
  'xpq': 'Mohegan-Pequot',
  'xpr': 'Parthian',
  'xps': 'Pisidian',
  'xpt': 'Punthamara',
  'xpu': 'Punic',
  'xpy': 'Puyo',
  'xqa': 'Karakhanid',
  'xqt': 'Qatabanian',
  'xra': 'Rarotongan',
  'xrb': 'Eastern Karaboro',
  'xre': 'Kreye',
  'xri': 'Krikati-Timbira',
  'xrm': 'Armazic',
  'xrn': 'Arin',
  'xrr': 'Raetic',
  'xrt': 'Aranama-Tamique',
  'xru': 'Marriammu',
  'xrw': 'Karawa',
  'xsa': 'Sabaean',
  'xsb': 'Sambal',
  'xsc': 'Scythian',
  'xsd': 'Sidetic',
  'xse': 'Sempan',
  'xsh': 'Shamang',
  'xsi': 'Sio',
  'xsj': 'Subi',
  'xsl': 'South Slavey',
  'xsm': 'Kasem',
  'xsn': 'Sanga',
  'xso': 'Solano',
  'xsp': 'Silopi',
  'xsq': 'Makhuwa-Saka',
  'xsr': 'Sherpa',
  'xss': 'Assan',
  'xsu': 'Sanumá',
  'xsv': 'Sudovian',
  'xsy': 'Saisiyat',
  'xta': 'Alcozauca Mixtec',
  'xtb': 'Chazumba Mixtec',
  'xtc': 'Katcha-Kadugli-Miri',
  'xtd': 'Diuxi-Tilantongo Mixtec',
  'xte': 'Ketengban',
  'xtg': 'Transalpine Gaulish',
  'xth': 'Yitha Yitha',
  'xti': 'Sinicahua Mixtec',
  'xtj': 'San Juan Teita Mixtec',
  'xtl': 'Tijaltepec Mixtec',
  'xtm': 'Magdalena Peñasco Mixtec',
  'xtn': 'Northern Tlaxiaco Mixtec',
  'xto': 'Tokharian A',
  'xtp': 'San Miguel Piedras Mixtec',
  'xtq': 'Tumshuqese',
  'xtr': 'Early Tripuri',
  'xts': 'Sindihui Mixtec',
  'xtt': 'Tacahua Mixtec',
  'xtu': 'Cuyamecalco Mixtec',
  'xtv': 'Thawa',
  'xtw': 'Tawandê',
  'xty': 'Yoloxochitl Mixtec',
  'xtz': 'Tasmanian',
  'xua': 'Alu Kurumba',
  'xub': 'Betta Kurumba',
  'xud': 'Umiida',
  'xug': 'Kunigami',
  'xuj': 'Jennu Kurumba',
  'xum': 'Umbrian',
  'xun': 'Unggaranggu',
  'xuo': 'Kuo',
  'xup': 'Upper Umpqua',
  'xur': 'Urartian',
  'xuu': 'Kxoe',
  'xve': 'Venetic',
  'xvi': 'Kamviri',
  'xvn': 'Vandalic',
  'xvo': 'Volscian',
  'xvs': 'Vestinian',
  'xwa': 'Kwaza',
  'xwc': 'Woccon',
  'xwd': 'Wadi Wadi',
  'xwe': 'Xwela Gbe',
  'xwg': 'Kwegu',
  'xwl': 'Western Xwla Gbe',
  'xwo': 'Written Oirat',
  'xwr': 'Kwerba Mamberamo',
  'xwt': 'Wotjobaluk',
  'xww': 'Wemba Wemba',
  'xxb': 'Boro (Ghana)',
  'xxk': 'Ke\'o',
  'xxm': 'Minkin',
  'xxr': 'Koropó',
  'xxt': 'Tambora',
  'xya': 'Yaygir',
  'xyb': 'Yandjibara',
  'xyj': 'Mayi-Yapi',
  'xyk': 'Mayi-Kulan',
  'xyl': 'Yalakalore',
  'xyt': 'Mayi-Thakurti',
  'xyy': 'Yorta Yorta',
  'xzh': 'Zhang-Zhung',
  'xzm': 'Zemgalian',
  'xzp': 'Ancient Zapotec',
};

export const useLanguageDisplay = () => {
  const getLanguageName = useMemo(() => {
    return (languageCode: string): string => {
      const normalizedCode = languageCode.toLowerCase();
      return LANGUAGE_MAP[normalizedCode] || languageCode.toUpperCase();
    };
  }, []);

  return { getLanguageName };
}; 