name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm audit --audit-level=moderate
        
      - name: TypeScript type checking
        run: npx tsc --noEmit
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Run tests
        run: npm run test:once
        
      - name: Run tests with coverage
        run: npm run test:coverage
        
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  build:
    name: Build & Bundle Analysis
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Analyze bundle size
        run: |
          echo "📦 Bundle Size Analysis"
          echo "======================="
          ls -lh dist/assets/
          echo ""
          echo "🔍 Detailed breakdown:"
          du -h dist/assets/* | sort -hr
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/
          retention-days: 1

  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/
          
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
        
      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 7

  performance-budget:
    name: Performance Budget Check
    runs-on: ubuntu-latest
    needs: lighthouse
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Download Lighthouse results
        uses: actions/download-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci/
          
      - name: Check Performance Budget
        run: |
          echo "🚀 Performance Budget Check"
          echo "==========================="
          
          # Extract performance scores from latest run
          PERF_SCORE=$(cat .lighthouseci/lhr-*.json | jq -r '.categories.performance.score * 100' | head -1)
          ACCESSIBILITY_SCORE=$(cat .lighthouseci/lhr-*.json | jq -r '.categories.accessibility.score * 100' | head -1)
          BEST_PRACTICES_SCORE=$(cat .lighthouseci/lhr-*.json | jq -r '.categories."best-practices".score * 100' | head -1)
          SEO_SCORE=$(cat .lighthouseci/lhr-*.json | jq -r '.categories.seo.score * 100' | head -1)
          
          echo "Performance: ${PERF_SCORE}%"
          echo "Accessibility: ${ACCESSIBILITY_SCORE}%"
          echo "Best Practices: ${BEST_PRACTICES_SCORE}%"
          echo "SEO: ${SEO_SCORE}%"
          echo ""
          
          # Set performance budgets
          PERF_BUDGET=80
          ACCESSIBILITY_BUDGET=95
          BEST_PRACTICES_BUDGET=90
          SEO_BUDGET=90
          
          # Check budgets
          if (( $(echo "$PERF_SCORE < $PERF_BUDGET" | bc -l) )); then
            echo "❌ Performance score ($PERF_SCORE%) is below budget ($PERF_BUDGET%)"
            exit 1
          fi
          
          if (( $(echo "$ACCESSIBILITY_SCORE < $ACCESSIBILITY_BUDGET" | bc -l) )); then
            echo "❌ Accessibility score ($ACCESSIBILITY_SCORE%) is below budget ($ACCESSIBILITY_BUDGET%)"
            exit 1
          fi
          
          if (( $(echo "$BEST_PRACTICES_SCORE < $BEST_PRACTICES_BUDGET" | bc -l) )); then
            echo "❌ Best Practices score ($BEST_PRACTICES_SCORE%) is below budget ($BEST_PRACTICES_BUDGET%)"
            exit 1
          fi
          
          if (( $(echo "$SEO_SCORE < $SEO_BUDGET" | bc -l) )); then
            echo "❌ SEO score ($SEO_SCORE%) is below budget ($SEO_BUDGET%)"
            exit 1
          fi
          
          echo "✅ All performance budgets met!" 